name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        python -m pip install -U pip setuptools
        pip install pyinstaller==3.5
    - name: Run a multi-line script
      run: |
        pwd
        ls
        pyinstaller --onefile ./source/helloWorld.py
        ls
 #   - uses: actions/upload-artifact@v1
 #     with:
 #       name: helloWorld
 #       path: helloWorld
